name: Deploy Render

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          echo "Installing requirements..."
          pip install -r requirements.txt
          pip install pytest mongomock

      - name: Install and run Black
        run: |
          pip install black
          black .

      - name: Run tests
        run: make test

      - name: Notifica o n8n
        run: |
          curl -X POST http://wondrous-seasnail-wired.ngrok-free.app//webhook-test/github-build  \
          -H "Content-Type: application/json" \
          -d '{"repository": "${{ github.repository }}", "status": "${{ job.status }}", "commit": "${{ github.sha }}"}'

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          echo "Deploy URL: $DEPLOY_URL"
          curl "$DEPLOY_URL"
